language: python
matrix:
  include:
  - python: 3.6
    dist: xenial
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: 3.9
    dist: xenial
addons:
  apt:
    packages:
    - libfreetype6-dev
    - libopenblas-dev
install:
- pip install cython
- pip install .
- pip install -U pytest "coverage<5"
services:
- xvfb
script: pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: hmcOyrNaBe3mssTOld57iD7IZfjnKQNNYO2Orwi3ZvMfyoIGmF0v0eqMJbAkvP2J3sLV3lW/wpdZtvFOMQk5x3DHIZ3V54gdHYWI5LiSL8I7Ntwqa/t/GmN+W8rQ6U/DmOGcqBA7d+Yo/+LU3QXggRgL4JrBJDqBWhYnAMsmOOVCOS/0K8e+v98/qmjD721q87MHWA+Cs+IZ5YrmKWuR0g1rn+zcEPRye3bupmQsUal+ij+13rjaKYxa3tC9GbpHi9/2sLHpM84AJS9ka6mVf46dmt68un4txb8OssPoVdaM0+10z8ZS2FyiYVV6+sho1S9Dkiqgfxz9YpKMJDQV72PQ2HqPGWBQghO5LL413nzOZTI/0j9CgUEMYgwdqVRU97whLz9kov95of5mDO3ljmCfHcxBF2j2ZGhJxyb2tXFBU3ty9N7Mn9nzK6MsnMv3qPljTJ7QfNrfrWqvNDMb+JaKK7rSyk7Nx4RydJ1Wg0R/3QJiq4p0+Hg+Ghpg5iKF1vS1S2EvK3m3grSmzWhN/GmmB77iWnmVjorLhbK2G7NJpyAWvB0yQea9edFNU/mqGhFHxGe1aZj7xRQW7DwDWuA8KDCOo64LKlCE7iTPgayVCSgUbCkmL6L7gYivSKlZYzkkHsgnQv8AfU550tcyncBkupkUm5bAzknqijA9FoE=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
